name: Build and push for dev

on:
  workflow_call:
    inputs:
      svace_enabled:
        description: "Enable svace build and analyze"
        type: boolean
        required: false

jobs:
  dev_build:
    runs-on: ubuntu-latest
    name: Dev build
    steps:
      - name: build
        env:
          SVACE_ENABLED: ${{ inputs.svace_enabled }}
        run: |
          echo "Svace enabled: $SVACE_ENABLED"