name: Job output

on:
  workflow_dispatch:        

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      job1_name: ${{ steps.set-output.outputs.name }}
    steps:
      - name: set output
        id: set-output
        run: echo "name=himax" >> $GITHUB_OUTPUT
        
      - name: access output
        run: echo ${{ steps.set-output.outputs.name }}

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: access job1 output
        run: echo ${{ needs.job1.outputs.job1_name }}
