name: Python script testing


on:
  # workflow_dispatch
  push:
    branches:
      - feature/python-script

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
      - name: init step
        run: |
          echo "Init step"
          ls -lah
