name: Python script testing


on:
  push:
    branches:
      - feature/python-script
  

env:
  WERF_CHANNEL: "ea"

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check runner fs structure
        run: |
          echo "Current dir" && pwd
          echo "Check files" && ls -lah

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Prepare files for collecting and deployment
        run: |
          mkdir -p ci/.helm/templates
          echo -e "project: deckhouse-channels\nconfigVersion: 1" | tee werf.yaml ci/werf.yaml
          echo "Print content of ci/werf.yaml" && cat ci/werf.yaml
          tee ci/.helm/templates/configmap.yaml << EOF
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: release-channels-data
          data:
            channels.yaml: |
          {{ $.Files.Get "channels.yaml" | indent 4 }}
          EOF

          echo "Print content of ci/.helm/templates/configmap.yaml" && cat ci/.helm/templates/configmap.yaml

      - name: Collect release versions
        run: python collect-released-versions.py

      - name: Print channels.yaml
        run: cat ci/.helm/channels.yaml

      - name: Install werf CLI  
        uses: werf/actions/install@v2

      - name: Converge
        uses: werf/actions/converge@v2
        with:
          channel: ${{env.WERF_CHANNEL}}
          kube-config-base64-data: "${{ secrets.WERF_KUBECONFIG_BASE64 }}"
          env: dev
        env:
          WERF_NAMESPACE: "deckhouse-web-dev"
          WERF_DIR: "ci"
          WERF_DEV: "true"