name: Python script testing


on:
  # workflow_dispatch
  push:
    branches:
      - feature/python-script

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Check runner fs structure
        run: |
          echo "Current dir" && pwd
          echo "Check files" && ls -lah

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Collect release versions
        run: python collect-released-versions.py
