name: Simple scheduled

on:
  schedule:
    - cron: "49 14 * * 2"
  workflow_dispatch:
    inputs:
      svace_enabled:
        description: 'Enable svace build and analyze'
        type: boolean
        required: false

jobs:
  test-job:
    runs-on: ubuntu-latest
    name: Test job
    steps:
      - name: test
        run: |
          echo "Started for \"Simple scheduled\""