name: Step output

on:
  workflow_dispatch:
    inputs:
      test_enabled:
        description: "enable lasy job"
        required: false
  # pull_request_target:
  #   types:
  #     - opened
  #     - labeled
  #     - reopened
  #     - synchronize
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
  push:
    branches:
      - main
      - release-*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test job
    steps:
      - name: Test job
        run: |
          echo "run dummy step"

  last_job:
    if: ${{ inputs.test_enabled == 'true' && always() }}
    runs-on: ubuntu-latest
    name: last job
    steps:
      - name: last job
        run: |
          echo "hello after job"

