name: Step output

on:
  workflow_dispatch:
    

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: set output
        id: set-output
        shell: bash
        run: |
          echo "greeting_message=Hello world!" >> $GITHUB_OUTPUT

      - name: get output
        run: |
          echo "${{ steps.set-output.outputs.greeting_message }}"
          
      - name: list env variables
        run: env
    
    
