name: Step output

on:
  workflow_dispatch:
  # pull_request_target:
  #   types:
  #     - opened
  #     - labeled
  #     - reopened
  #     - synchronize
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
  push:
    branches:
      - main
      - release-*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: Add ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SUPERSECRET }}    
            ${{ secrets.secretValue }}

      - name: Add ssh_known_hosts
        continue-on-error: true
        run: |
          host="example-host.domain"

          host_ip=$(nslookup "$host" | awk '/^Address: / { print $2 }')
          echo "::add-mask::$host_ip"

          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          HOST_KEYS=$(ssh-keyscan -H "$host" 2>/dev/null)
          while IFS= read -r KEY_LINE; do
              CONSTANT_PART=$(awk '{print $2, $3}' <<< "$KEY_LINE")
              if grep -q "$CONSTANT_PART" ~/.ssh/known_hosts; then
                  ssh-keygen -R $host
                  ssh-keygen -R $host_ip
              fi
              echo "$KEY_LINE" >> ~/.ssh/known_hosts
          done <<< "$HOST_KEYS"  

      - name: Check expressions
        env:
          MY_VAR: ${{ secrets.verySecret }}
        run: |
          echo $MY_VAR

