name: Step output

on:
  workflow_dispatch:
  # pull_request_target:
  #   types:
  #     - opened
  #     - labeled
  #     - reopened
  #     - synchronize
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
  push:
    branches:
      - main
      - release-*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: Add ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.secretValue }}
            ${{ secrets.SUPERSECRET }}    

      - name: Check expressions
        env:
          MY_VAR: ${{ secrets.verySecret }}
        run: |
          echo $MY_VAR

