name: test output

on:
  push:

jobs:
  set_output:
    runs-on: ubuntu-latest
    outputs:
      var: ${{ steps.set_var.outputs.test_var }}
    steps:
      - name: set_var
        id: set_var
        run: |
          echo "test_var=true" >> $GITHUB_OUTPUT

      - name: check
        run: |
          cat "$GITHUB_OUTPUT"


  print_output:
    runs-on: ubuntu-latest
    needs: set_output
    steps:
      - name: Print
        run: |
          echo "Output var: ${{ needs.set_output.outputs.var }}"